/* =========================================================
   /api/admin/services — Our Services CMS endpoint.

   GET  → returns current data/services.json
   PUT  → validates new services data, regenerates packages.html +
          add-ons.html + js/inquiry-section.js by replacing the CMS
          marker-delimited sections, then commits all 4 files in a
          single atomic git commit (Tree API).

   ~30s after save, Vercel redeploys and the new packages + add-ons
   appear on:
     /packages, /add-ons, the inquiry form dropdown + checkboxes,
     the Package List cart, and (via runtime data attrs) every page
     that surfaces a package or add-on.

   Note: area pages also surface a "pick a package" section. They get
   regenerated by `npm run regen` locally when the user wants area
   pages to reflect the latest data; the API skips them here to keep
   the commit small and fast.
   ========================================================= */

import { requireAuth } from "../_lib/auth.js";
import { getJson, getFile, commitMultiple } from "../_lib/github.js";
import {
  renderPackagesGrid,
  renderEveryPackageList,
  renderAddonsContainer,
  renderInquiryArrays,
  replaceMarker,
} from "../_lib/services-render.js";

const DATA_PATH = "data/services.json";
const PKG_HTML_PATH = "packages.html";
const ADD_HTML_PATH = "add-ons.html";
const INQ_JS_PATH = "js/inquiry-section.js";

async function handler(req, res) {
  try {
    if (req.method === "GET") {
      const file = await getJson(DATA_PATH);
      if (!file) return res.status(404).json({ error: "services.json not found" });
      return res.status(200).json({ services: file.data });
    }

    if (req.method === "PUT") {
      let body = req.body;
      if (typeof body === "string") body = JSON.parse(body);
      const incoming = body?.services;
      if (!incoming) return res.status(400).json({ error: "Missing services object" });

      const v = validate(incoming);
      if (v.error) return res.status(400).json({ error: v.error });

      // Read current source files in parallel
      const [pkgFile, addFile, inqFile] = await Promise.all([
        getFile(PKG_HTML_PATH),
        getFile(ADD_HTML_PATH),
        getFile(INQ_JS_PATH),
      ]);
      if (!pkgFile || !addFile || !inqFile) {
        return res.status(500).json({ error: "Could not read source files from repo" });
      }

      // Regenerate each section
      const newPackagesGrid = renderPackagesGrid(incoming.packages);
      const newEveryPkg = renderEveryPackageList(incoming.everyPackageIncludes || []);
      const newAddonsContainer = renderAddonsContainer(incoming.addonCategories);
      const newInquiryArrays = renderInquiryArrays(incoming);

      // Splice into the source HTML/JS
      let newPkgHtml = replaceMarker(pkgFile.content, "CMS:PACKAGES_GRID", newPackagesGrid);
      newPkgHtml = replaceMarker(newPkgHtml, "CMS:EVERY_PACKAGE", newEveryPkg);
      const newAddHtml = replaceMarker(addFile.content, "CMS:ADDONS_CONTAINER", newAddonsContainer);
      const newInqJs = replaceMarker(inqFile.content, "CMS:INQUIRY_DATA", newInquiryArrays);

      // Pretty-print services.json
      const newServicesJson = JSON.stringify(incoming, null, 2) + "\n";

      // Atomic commit — all 4 files in a single commit (Tree API)
      const commitSha = await commitMultiple(
        [
          { path: DATA_PATH, content: newServicesJson },
          { path: PKG_HTML_PATH, content: newPkgHtml },
          { path: ADD_HTML_PATH, content: newAddHtml },
          { path: INQ_JS_PATH, content: newInqJs },
        ],
        `CMS: update services\n\nBy admin: ${req.user?.username || "admin"}`
      );

      return res.status(200).json({
        ok: true,
        commitSha,
        services: incoming,
        message: "Saved. Republishing — live in ~30 seconds.",
      });
    }

    res.setHeader("Allow", "GET, PUT");
    return res.status(405).json({ error: "Method not allowed" });
  } catch (err) {
    console.error("/api/admin/services error:", err);
    return res.status(500).json({ error: err.message || "Internal error" });
  }
}

/* ---------- Validation ---------- */
function validate(s) {
  const errors = [];
  if (!Array.isArray(s.packages) || s.packages.length === 0) errors.push("packages must be a non-empty array");
  if (!Array.isArray(s.addonCategories)) errors.push("addonCategories must be an array");

  if (Array.isArray(s.packages)) {
    s.packages.forEach((p, i) => {
      if (!p.id || !p.name) errors.push(`package #${i + 1}: missing id or name`);
      if (typeof p.price !== "number" || p.price < 0) errors.push(`package "${p.name}": price must be a non-negative number`);
      if (!Array.isArray(p.features)) errors.push(`package "${p.name}": features must be an array`);
    });
  }

  if (Array.isArray(s.addonCategories)) {
    s.addonCategories.forEach((c, i) => {
      if (!c.label) errors.push(`category #${i + 1}: missing label`);
      if (!Array.isArray(c.addons)) errors.push(`category "${c.label}": addons must be an array`);
      else {
        c.addons.forEach((a, j) => {
          if (!a.id || !a.name) errors.push(`addon "${c.label}" #${j + 1}: missing id or name`);
          if (typeof a.price !== "number" || a.price < 0) errors.push(`addon "${a.name}": price must be a non-negative number`);
        });
      }
    });
  }

  if (errors.length) return { error: errors.join("; ") };
  return { ok: true };
}

export default requireAuth(handler);
